Month 7/step 2
DenDEADLIFT/react-stellar-burger pull request #2
Opened 2023-05-11 04:31 UTC by DenDEADLIFT

2023-05-11 15:55 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Сделали проверку успешности запроса
- Вынесли запрос в отдельный файл
- Хорошая работа с `propTypes`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- обработчик закрытия попапа по ESC не будет удаляться при закрытии
- Поправьте propTypes у некоторых компонентов
 
Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-11 15:55 UTC, andryxxa93 commented on src/components/burgeringredients/burgeringredients.jsx
> +    data: PropTypes.array,
**Необходимо исправить**
Тут необходимо так же указать что под `data` приходит конкретно. Так же как и в `BurgerConstructor `

2023-05-11 15:55 UTC, andryxxa93 commented on src/components/burgeringredients/ingridients/ingridients.jsx
> +  calories: PropTypes.number.isRequired,
**Необходимо исправить**
Тут необходимо так же использовать `ingredientPropType`. Чтобы это сделать необходимо передавать  в компонент не поля по отдельности, а просто весь объект ингредиента

2023-05-11 15:55 UTC, andryxxa93 commented on src/components/ingredientdetails/ingredientdetails.jsx
> +IngredientDetails.propTypes = {
**Необходимо исправить**
У вас неправильно тут указано название пропса - нужно `data` а не `props`. Проверьте во всём проекте.

2023-05-11 15:55 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +    React.useEffect(() => {
**Надо исправить**
Обработчик закрытия попапа должен добавляться при открытии попапа и удаляться при закрытии. Сейчас обработчик не будет удаляться при закрытии попапа т.к. из хука useEffect нужно возвращать колбэк отписки. Должно быть примерно так:

```
   useEffect(() => {
      const handleESCclose = () => {............} //обработчик события
      document.addEventListener("keydown", handleESCclose); //навешиваем обработчик
	  
	  //возвращаем колбэк отписки, который  будет вызван при размонтировании компонента
      return () => document.removeEventListener("keydown", handleESCclose)                                                                                               
   }, [onClose])
```

2023-05-11 15:55 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        console.log(`Ошбика ${reject.status}`)
**Можно лучше**
хорошо, что обрабатывается ошибка запроса к фзш api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2023-05-11 18:08 UTC, DenDEADLIFT commented on src/components/app/app.jsx
> +        console.log(`Ошбика ${reject.status}`)
Интересно! Я подумаю как это сделать, на выходных

2023-05-12 08:19 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        console.log(`Ошбика ${reject.status}`)
У вас уже создана универсальная модалка - вы можете там показывать сообщение об ошибке)

2023-05-12 08:21 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-27 06:35 UTC, merged